//! SpacetimeDB SDK wiring for live play. Compiled only with `--features live`
//! (see `net/mod.rs` for the `spacetime generate` step that produces the
//! `module_bindings` this file imports).
//!
//! Design: this module owns NO game logic. It connects, subscribes, and on every
//! relevant table change calls into [`LiveBridge`] (which is itself fully tested
//! without any SpacetimeDB dependency), then turns the bridge's answers into
//! `submit_bid` / `submit_word` reducer calls. The connection runs on its own
//! thread; the bridge is shared behind a `Mutex`.
//!
//! The SDK 2.x patterns here (`DbConnection::builder()....build()`,
//! `subscription_builder().subscribe([...])`, `ctx.db.<table>().on_insert(..)`,
//! `ctx.reducers.<reducer>(..)`) follow the official Rust quickstart. The table
//! row field names follow the verbatim `scrabblebot` module schema.

use std::fs;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use crate::bridge::{counts_from_holdings, LiveBridge};
use crate::persona::Persona;

// Generated by `spacetime generate --lang rust` (see net/mod.rs).
use super::module_bindings::*;

const HOST: &str = "https://maincloud.spacetimedb.com";
const DB_NAME: &str = "scrabblebot";

type Shared = Arc<Mutex<LiveBridge>>;

/// Entry point for `bard play` (with `--features live`).
pub fn run_live(_args: &[String]) {
    let persona = std::env::var("BARD_PERSONA")
        .ok()
        .and_then(|n| Persona::by_name(&n))
        .unwrap_or_else(Persona::shakespeare);

    println!(
        "The Bard going live as '{}' -> module `{DB_NAME}` @ {HOST}",
        persona.name
    );

    let bridge: Shared = Arc::new(Mutex::new(LiveBridge::new(persona)));

    let conn = DbConnection::builder()
        .on_connect(|_ctx, _identity, token| {
            save_token(&token);
            println!("connected.");
        })
        .on_connect_error(|_ctx, err| eprintln!("connect error: {err}"))
        .on_disconnect(|_ctx, err| eprintln!("disconnected: {err:?}"))
        .with_token(load_token())
        .with_module_name(DB_NAME)
        .with_uri(HOST)
        .build()
        .expect("failed to connect to SpacetimeDB");

    register_callbacks(&conn, bridge.clone());

    conn.subscription_builder()
        .on_applied(|_ctx| println!("subscriptions applied; waiting for a match…"))
        .on_error(|_ctx, err| eprintln!("subscription error: {err}"))
        .subscribe([
            "SELECT * FROM match_state",
            "SELECT * FROM auction",
            "SELECT * FROM auction_result",
            "SELECT * FROM match_participant",
            "SELECT * FROM word_play",
            "SELECT * FROM bot_credential",
            "SELECT * FROM my_rack",
        ]);

    // Enter the rolling lobby. `join_lobby` is idempotent; we also re-join after a
    // match ends (handled in the match_state callback).
    let _ = conn.reducers.join_lobby();

    conn.run_threaded()
        .join()
        .expect("connection thread panicked");
}

/// Register all table callbacks. Each captures its own clone of the shared bridge.
fn register_callbacks(conn: &DbConnection, bridge: Shared) {
    // --- our private rack view: rebuild Counts whenever it changes ---
    let b = bridge.clone();
    conn.db.my_rack().on_insert(move |ctx, _row| sync_my_rack(ctx, &b));
    let b = bridge.clone();
    conn.db.my_rack().on_update(move |ctx, _old, _new| sync_my_rack(ctx, &b));

    // --- a tile goes up for auction: decide and submit our bid ---
    let b = bridge.clone();
    conn.db.auction().on_insert(move |ctx, auction| {
        // Only bid on open auctions.
        if !is_auction_open(auction) {
            return;
        }
        let bid = {
            let mut g = b.lock().unwrap();
            ensure_match_context(ctx, &mut g);
            g.on_auction_open(&auction.letter)
        };
        if let Some(amount) = bid {
            let _ = ctx.reducers.submit_bid(auction.id, amount);
        }
    });

    // --- auction resolved: update supply + (if it was us) our balance/rack ---
    let b = bridge.clone();
    conn.db.auction_result().on_insert(move |ctx, res| {
        {
            let mut g = b.lock().unwrap();
            g.on_auction_result(res.winner_bot_id, &res.letter, res.paid);
        }
        // Winning a tile may unlock a word.
        try_play_word(ctx, &b);
    });

    // --- any word played: feed the public stream into opponent modelling ---
    let b = bridge.clone();
    conn.db.word_play().on_insert(move |_ctx, wp| {
        let mut g = b.lock().unwrap();
        g.on_word_played(wp.bot_id, &wp.word, wp.total_reward);
    });

    // --- public participant snapshots: authoritative balances/scores ---
    let b = bridge.clone();
    conn.db
        .match_participant()
        .on_insert(move |_ctx, p| feed_participant(&b, p));
    let b = bridge.clone();
    conn.db
        .match_participant()
        .on_update(move |_ctx, _old, p| feed_participant(&b, p));

    // --- match lifecycle: start a match, and re-join the lobby when one ends ---
    let b = bridge.clone();
    conn.db.match_state().on_insert(move |ctx, m| on_match_state(ctx, &b, m));
    let b = bridge.clone();
    conn.db
        .match_state()
        .on_update(move |ctx, _old, m| on_match_state(ctx, &b, m));
}

fn feed_participant(bridge: &Shared, p: &MatchParticipant) {
    let mut g = bridge.lock().unwrap();
    g.on_participant(p.bot_id, p.balance, p.score);
}

/// Rebuild our rack from all current `my_rack` rows, sync balance/score, and try
/// to play a word.
fn sync_my_rack(ctx: &EventContext, bridge: &Shared) {
    let holdings: Vec<(String, u32)> = ctx
        .db
        .my_rack()
        .iter()
        .map(|h| (h.letter.clone(), h.count))
        .collect();
    let counts = counts_from_holdings(holdings.iter().map(|(l, c)| (l.as_str(), *c)));

    {
        let mut g = bridge.lock().unwrap();
        ensure_match_context(ctx, &mut g);
        let (balance, score) = self_balance_score(ctx, &g);
        g.on_my_rack(counts, balance, score);
    }
    try_play_word(ctx, bridge);
}

/// If the bridge wants to play a word, submit it.
fn try_play_word(ctx: &EventContext, bridge: &Shared) {
    let (match_id, word) = {
        let g = bridge.lock().unwrap();
        match (g.match_id(), g.next_word_to_play()) {
            (Some(mid), Some(w)) => (mid, w),
            _ => return,
        }
    };
    let _ = ctx.reducers.submit_word(match_id, word);
}

/// React to `match_state` changes: capture the running match, or re-enter the
/// lobby once it ends.
fn on_match_state(ctx: &EventContext, bridge: &Shared, m: &Match) {
    match m.status {
        MatchStatus::Running => {
            let me = match my_bot_id(ctx) {
                Some(id) => id,
                None => return,
            };
            // Gather every participant id in this match.
            let players: Vec<u64> = ctx
                .db
                .match_participant()
                .iter()
                .filter(|p| p.match_id == m.id)
                .map(|p| p.bot_id)
                .collect();
            if players.iter().any(|&p| p == me) {
                let mut g = bridge.lock().unwrap();
                // start_balance is the module constant; tiles_to_auction is what's
                // left after dealing starting racks (bag_total - players*5).
                let start_balance = 100;
                let tiles_to_auction = m.bag_total.saturating_sub(players.len() as u32 * 5);
                g.start_match(me, players, start_balance, tiles_to_auction, m.id);
            }
        }
        MatchStatus::Ended => {
            // Roll into the next lobby.
            let _ = ctx.reducers.join_lobby();
        }
        MatchStatus::Lobby => {}
    }
}

/// Make sure the bridge knows our bot id even before the first match_state event.
fn ensure_match_context(ctx: &EventContext, g: &mut LiveBridge) {
    if g.me.is_none() {
        if let Some(id) = my_bot_id(ctx) {
            g.set_me(id);
        }
    }
}

/// Resolve our own bot id from `bot_credential` (identity -> bot_id).
fn my_bot_id(ctx: &EventContext) -> Option<u64> {
    let me = ctx.identity();
    ctx.db
        .bot_credential()
        .iter()
        .find(|c| c.identity == me)
        .map(|c| c.bot_id)
}

/// Our authoritative balance/score from the public participant table.
fn self_balance_score(ctx: &EventContext, g: &LiveBridge) -> (i64, i64) {
    if let Some(me) = g.me {
        if let Some(p) = ctx.db.match_participant().iter().find(|p| p.bot_id == me) {
            return (p.balance, p.score);
        }
    }
    (100, 0) // sensible default before the first snapshot
}

/// Is this auction currently open for bids?
fn is_auction_open(a: &Auction) -> bool {
    matches!(a.status, AuctionStatus::Open)
}

// --- token persistence (mirrors the official starter) ----------------------

fn token_path() -> PathBuf {
    let name = std::env::var("BOT_NAME").unwrap_or_else(|_| "bard".to_string());
    PathBuf::from(format!(".token-{name}"))
}

fn load_token() -> Option<String> {
    if let Ok(tok) = std::env::var("BOT_TOKEN") {
        if !tok.trim().is_empty() {
            return Some(tok.trim().to_string());
        }
    }
    fs::read_to_string(token_path())
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
}

fn save_token(token: &str) {
    let _ = fs::write(token_path(), token);
}
